name: workflow-trigger

on:push:
  branches:
    - main
  paths:
    - 'workflow-trigger/**'

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Say hello
        run: echo "Hello World"

  Failed-step:
    runs-on: ubuntu-latest
    steps:
      - name: Failed steps 
        run: |
          echo "I will fail"
          exit 1

  echo-goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: Bye 
        run: echp "Goodbye"


  
